(()=>{
const addCss=()=>{const st=document.createElement('style');st.textContent=`
.focusTree{min-width:920px;min-height:680px;padding:44px 60px 170px;display:flex;flex-direction:column;align-items:center;gap:24px}.focusLevel{display:flex;justify-content:center;align-items:center;gap:16px;position:relative;min-height:108px}.personNode{width:205px;min-height:92px;border:1px solid rgba(255,255,255,.13);border-radius:22px;background:linear-gradient(145deg,#162135,#0d1522);color:#fff;padding:14px 15px;text-align:left;box-shadow:0 16px 40px rgba(0,0,0,.2);position:relative}.personNode.active{border-color:#e8bc72;box-shadow:0 0 0 2px rgba(232,188,114,.15),0 22px 55px rgba(0,0,0,.32);background:linear-gradient(145deg,#26334b,#111a29)}.nodeTop{display:flex;align-items:center;gap:10px}.nodeAvatar{width:40px;height:40px;border-radius:14px;display:grid;place-items:center;background:linear-gradient(135deg,#e8bc72,#99652f);color:#241606;font-weight:900}.female .nodeAvatar{background:linear-gradient(135deg,#efc6d7,#9b5777);color:#2a101b}.nm{font-weight:820;line-height:1.15}.nodeSub{display:block;color:#96a1b3;font-size:.7rem;margin-top:7px;line-height:1.35}.nodeBadge{display:inline-flex;margin-top:7px;padding:4px 7px;border-radius:999px;font-size:.6rem;background:rgba(255,255,255,.06);color:#c8d1de}.union{display:flex;align-items:center;gap:9px}.unionMark{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;border:1px solid rgba(232,188,114,.4);color:#e8bc72;background:#17130d}.connectorV{width:2px;height:26px;background:linear-gradient(#e8bc72,rgba(232,188,114,.12))}.siblingWrap{display:flex;gap:14px;align-items:center}.youBadge{position:absolute;top:-9px;right:12px;background:#e8bc72;color:#241606;padding:4px 7px;border-radius:999px;font-size:.56rem;font-weight:900}.branchToolbar{position:sticky;left:12px;top:8px;z-index:10;display:flex;gap:7px;width:max-content;padding:7px}.branchToolbar button{border:1px solid rgba(255,255,255,.1);background:rgba(13,20,32,.92);color:#dce4ed;border-radius:999px;padding:9px 12px;font-weight:760}.branchToolbar button.active{background:#e8bc72;color:#241606}.branchHint{color:#96a1b3;font-size:.72rem;text-align:center}.frow{grid-auto-columns:205px!important}.fcard{display:none!important}@media(max-width:680px){.focusTree{min-width:750px;min-height:620px;padding:34px 42px 170px;gap:20px}.personNode{width:185px;min-height:86px;border-radius:19px;padding:12px}.nm{font-size:.84rem}.nodeSub{font-size:.64rem}.nodeAvatar{width:36px;height:36px;border-radius:12px}.focusLevel{gap:11px}.branchToolbar{top:5px}.directoryGrid{grid-template-columns:1fr!important}}
`;document.head.appendChild(st)};
addCss();
const father=byId('veera-venkata-satyanarayana'),mother=byId('naga-satya-mani');
let brother=byId('venkata-siva-subhash');
if(!brother){brother=normalize({id:'venkata-siva-subhash',fullName:'Venkata Siva Subhash',surname:'Bandiguptapu',gender:'Male',dob:'1986-12-13',ancestralVillage:'Allavaram',education:'M.B.A. — recorded in inherited genealogy',generationHint:6,parents:['veera-venkata-satyanarayana','naga-satya-mani'],spouses:[],children:[],confidence:'familyrecord',sourceNote:'Inherited genealogy records Venkata Siva Subhash, M.B.A., 13-12-1986 as a son of Veera Venkata Satyanarayana and Kankipati Naga Satya Mani.'});people.push(brother)}
for(const p of [father,mother])if(p&&!p.children.includes(brother.id))p.children.unshift(brother.id);
const union=(a,b)=>[...new Set([...(a||[]),...(b||[])])];brother.parents=union(brother.parents,['veera-venkata-satyanarayana','naga-satya-mani']);
try{sset(KEY,JSON.stringify({version:4,updatedAt:new Date().toISOString(),people}))}catch(e){}
let treeMode='branch';
window.nodeCard2=(p,label='')=>`<button class="personNode ${p.id===current?'active':''} ${p.gender==='Female'?'female':''}" data-id="${p.id}">${p.id==='satya-sundar-kumar'?'<span class="youBadge">YOU</span>':''}<div class="nodeTop"><span class="nodeAvatar">${initials(p)}</span><span class="nm">${fullName(p)}</span></div><span class="nodeSub">${[p.dob||p.birthYear,p.education,p.occupation,p.ancestralVillage].filter(Boolean).slice(0,2).join(' • ')||conf(p.confidence)}</span>${label?`<span class="nodeBadge">${label}</span>`:''}</button>`;
window.familyContext2=p=>{const parents=(p.parents||[]).map(byId).filter(Boolean),spouses=(p.spouses||[]).map(byId).filter(Boolean),ids=new Set();parents.forEach(x=>(x.children||[]).forEach(id=>{if(id!==p.id)ids.add(id)}));return{parents,spouses,siblings:[...ids].map(byId).filter(Boolean),children:(p.children||[]).map(byId).filter(Boolean)}};
window.renderFallbackGraph=()=>{const fb=document.getElementById('fallback'),p=byId(current),c=familyContext2(p);fb.classList.add('show');let body;if(treeMode==='branch'){const parents=c.parents.length?c.parents.map(x=>nodeCard2(x,'Parent')).join('<span class="unionMark">+</span>'):'<div class="empty">Parents not linked</div>';const self=c.spouses.length?`<div class="union">${nodeCard2(p,'Selected')}<span class="unionMark">♥</span>${c.spouses.map(x=>nodeCard2(x,'Spouse')).join('')}</div>`:nodeCard2(p,'Selected');body=`<div class="focusTree"><div class="focusLevel">${parents}</div><div class="connectorV"></div><div class="focusLevel"><div class="siblingWrap">${c.siblings.map(x=>nodeCard2(x,'Sibling')).join('')}</div>${self}</div><div class="connectorV"></div><div class="focusLevel">${c.children.length?c.children.map(x=>nodeCard2(x,'Child')).join(''):'<div class="empty">No children recorded</div>'}</div><div class="branchHint">Tap anyone to refocus · drag/scroll left, right, up or down</div></div>`}else{const g=groups();body=`<div class="fallbackTree">${g.map((arr,i)=>`<section class="fgen"><div class="fgenHead">Generation ${i+1}<br><span>${arr.length} people</span></div><div class="frow">${arr.map(x=>nodeCard2(x)).join('')}</div></section>`).join('')}</div>`}fb.innerHTML=`<div class="branchToolbar"><button id="branchMode" class="${treeMode==='branch'?'active':''}">Family branch</button><button id="allMode" class="${treeMode==='all'?'active':''}">All generations</button></div><div class="box">${body}</div>`;fb.querySelectorAll('.personNode').forEach(b=>b.onclick=()=>selectPerson(b.dataset.id,true));document.getElementById('branchMode').onclick=()=>{treeMode='branch';renderFallbackGraph()};document.getElementById('allMode').onclick=()=>{treeMode='all';renderFallbackGraph()};requestAnimationFrame(()=>fb.querySelector('.personNode.active')?.scrollIntoView({behavior:'smooth',block:'center',inline:'center'}))};
const oldSelect=selectPerson;window.selectPerson=(id,animate)=>{oldSelect(id,animate);if(!cy)renderFallbackGraph()};
if(document.getElementById('centerMap'))document.getElementById('centerMap').onclick=()=>document.querySelector('.personNode.active')?.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});
render();
})();